In [2]:
import pymongo

In [1]:
import pandas as pd

In [10]:
df = pd.read_parquet("/Users/yulin/workspace/extreme_quant/data/parquet/600000.SSE_DAILY.parquet")

In [11]:
df.head()

             Open  Close   High    Low      Volume       Amount trade_status
Date
2000-01-04  24.98  25.57  25.78  24.75   4496100.0  113946783.0           交易
2000-01-05  25.57  25.28  25.98  25.15   5252800.0  134465427.0           交易
2000-01-06  25.18  25.99  26.30  25.05   6229700.0  160059798.0           交易
2000-01-07  26.30  26.90  27.50  26.12  21355300.0  575751082.0           交易
2000-01-10  27.00  27.25  27.85  26.71  16539700.0  450453518.0           交易

In [7]:
df.trade_status.value_counts()

交易     5371
停牌      118
XD       15
DR        7
N         2
XR        1
待核查       0
Name: trade_status, dtype: int64

In [8]:
df=df[df["trade_status"]=="停牌"]

In [9]:
df.head()

             Open  Close   High    Low  Volume  Amount trade_status
Date
2000-05-08  25.00  25.00  25.00  25.00     0.0     0.0           停牌
2000-11-22  22.03  22.03  22.03  22.03     0.0     0.0           停牌
2001-05-28  20.25  20.25  20.25  20.25     0.0     0.0           停牌
2001-09-05  15.82  15.82  15.82  15.82     0.0     0.0           停牌
2002-02-04  14.14  14.14  14.14  14.14     0.0     0.0           停牌

In [14]:
df.loc["2000-04-25":"2000-05-15"]

             Open  Close   High    Low     Volume       Amount trade_status
Date
2000-04-25  24.81  24.84  25.09  24.78  2309500.0   57489169.0           交易
2000-04-26  24.88  25.00  25.57  24.80  3559400.0   89234644.0           交易
2000-04-27  25.00  24.74  25.20  24.68  3284200.0   81550296.0           交易
2000-04-28  24.74  25.00  25.00  24.65  3210800.0   79526614.0           交易
2000-05-08  25.00  25.00  25.00  25.00        0.0          0.0           停牌
2000-05-09  24.90  24.43  24.90  24.35  2606100.0   63808332.0           交易
2000-05-10  24.40  24.00  24.51  23.98  5873800.0  141397664.0           交易
2000-05-11  24.00  23.90  24.27  23.80  3388300.0   81370247.0           交易
2000-05-12  23.93  23.94  24.10  23.85  2969300.0   71131310.0           交易
2000-05-15  23.95  23.06  24.00  23.01  4078300.0   94939549.0           交易

In [42]:
import tushare as ts
ts.set_token("b9d8623c7dbde160e75147e2b47588810dd8dc3033ec8cadc9f64f53")
pro = ts.pro_api()
df = pro.trade_cal(exchange='SSE', start_date='1989', end_date='2030')

In [45]:
# df.reset_index()
# df.set_index("cal_date", inplace=True)
df.head()
df.to_csv("test.csv")

In [46]:
df = pd.read_csv("test.csv")
df.head()

   cal_date exchange  is_open  pretrade_date
0  19901219      SSE        1            NaN
1  19901220      SSE        1     19901219.0
2  19901221      SSE        1     19901220.0
3  19901222      SSE        0     19901221.0
4  19901223      SSE        0     19901221.0

In [41]:
df.index

RangeIndex(start=0, stop=12000, step=1)

In [30]:
from enum import Enum
class Exchange(Enum):
    SSE = 0         # 上交所
    SZSE = 1        # 深交所
    CFFEX = 2       # 中金所
    SHFE = 3        # 上期所
    CZCE = 4        # 郑商所
    DCE = 5         # 大商所
    INE = 6         # 上能源

In [32]:
Exchange.SSE.name

'SSE'

In [1]:
import tushare as ts

ts.set_token("b9d8623c7dbde160e75147e2b47588810dd8dc3033ec8cadc9f64f53")
PRO = ts.pro_api()

In [114]:
df_symbol = PRO.stock_basic(exchange="SSE", list_status='L', fields='ts_code,symbol,name,area,industry,list_date,list_status,fullname,exchange,market,is_hs,curr_type')

In [59]:
df_symbol.set_index("ts_code", inplace=True)

In [117]:
for x in df_symbol.ts_code:
    print(x) 
    break

600000.SH

In [58]:
df_symbol.index[0]

0

In [41]:
df = PRO.trade_cal(exchange="SZSE,SSE", start_date='1989', end_date='2030')

In [42]:
df.head()

Empty DataFrame
Columns: [exchange, cal_date, is_open, pretrade_date]
Index: []

In [36]:
df.exchange.value_counts()

SZSE    11505
Name: exchange, dtype: int64

In [62]:
df = PRO.query("daily", ts_code="600602.SH", start_date="19900101",
                   end_date="20300101")

In [63]:
from data.tushare_api import *

In [118]:
df1 = get_symbol_hist("600602.SH", start_date="20191201", end_date="20191210")

In [93]:
df1

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,600602.SH,20191210,8.14,8.22,8.10,8.19,8.16,0.03,0.3676,61111.63,49869.217
1,600602.SH,20191209,8.09,8.19,8.04,8.16,8.06,0.10,1.2407,68311.12,55465.699
2,600602.SH,20191206,8.07,8.11,8.00,8.06,8.11,-0.05,-0.6165,52099.91,41926.983
3,600602.SH,20191205,8.05,8.15,7.99,8.11,8.03,0.08,0.9963,81254.77,65569.553
4,600602.SH,20191204,8.03,8.14,7.97,8.03,8.08,-0.05,-0.6188,52009.90,41914.993
5,600602.SH,20191203,7.92,8.10,7.87,8.08,7.88,0.20,2.5381,58209.52,46490.771
6,600602.SH,20191202,7.91,8.01,7.85,7.88,7.97,-0.09,-1.1292,40127.22,31745.080

In [154]:
df2 = get_symbol_hist("600720.SH,600006.SH", start_date="20000101", end_date="")

In [155]:
df2

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,600720.SH,20221212,11.30,11.33,11.06,11.07,11.36,-0.29,-2.5528,87378.54,97491.851
1,600006.SH,20221212,6.24,6.24,6.10,6.11,6.25,-0.14,-2.2400,229832.86,141213.285
2,600720.SH,20221209,11.24,11.39,11.14,11.36,11.22,0.14,1.2478,102615.85,115767.527
3,600006.SH,20221209,6.26,6.34,6.20,6.25,6.23,0.02,0.3210,242641.29,151702.405
4,600720.SH,20221208,11.14,11.38,11.08,11.22,11.23,-0.01,-0.0890,79695.77,89322.518
...,...,...,...,...,...,...,...,...,...,...,...
5995,600006.SH,20100609,4.92,5.06,4.90,5.05,4.93,0.12,2.4300,97383.53,48585.468
5996,600720.SH,20100608,12.78,13.03,12.70,12.93,12.86,0.07,0.5400,60054.22,77286.362
5997,600006.SH,20100608,4.85,5.00,4.85,4.93,4.87,0.06,1.2300,67001.18,33029.197
5998,600720.SH,20100607,12.54,13.08,12.40,12.86,12.86,0.00,0.0000,67639.15,86731.135
5999,600006.SH,20100607,4.83,4.91,4.81,4.87,4.96,-0.09,-1.8100,51013.86,24814.115

In [121]:
df1.set_index("trade_date", inplace=True)
df2.set_index("trade_date", inplace=True)
df1.index = pd.to_datetime(df1.index)
df2.index = pd.to_datetime(df2.index)

In [122]:
df1

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2019-12-10,600602.SH,8.14,8.22,8.10,8.19,8.16,0.03,0.3676,61111.63,49869.217
2019-12-09,600602.SH,8.09,8.19,8.04,8.16,8.06,0.10,1.2407,68311.12,55465.699
2019-12-06,600602.SH,8.07,8.11,8.00,8.06,8.11,-0.05,-0.6165,52099.91,41926.983
2019-12-05,600602.SH,8.05,8.15,7.99,8.11,8.03,0.08,0.9963,81254.77,65569.553
2019-12-04,600602.SH,8.03,8.14,7.97,8.03,8.08,-0.05,-0.6188,52009.90,41914.993
2019-12-03,600602.SH,7.92,8.10,7.87,8.08,7.88,0.20,2.5381,58209.52,46490.771
2019-12-02,600602.SH,7.91,8.01,7.85,7.88,7.97,-0.09,-1.1292,40127.22,31745.080

In [131]:
df3=pd.concat([df1, df2], axis=0)

In [132]:
df3 = df3[~df3.index.duplicated(keep='first')]

In [133]:
df3

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2019-12-10,600602.SH,8.14,8.22,8.10,8.19,8.16,0.03,0.3676,61111.63,49869.217
2019-12-09,600602.SH,8.09,8.19,8.04,8.16,8.06,0.10,1.2407,68311.12,55465.699
2019-12-06,600602.SH,8.07,8.11,8.00,8.06,8.11,-0.05,-0.6165,52099.91,41926.983
2019-12-05,600602.SH,8.05,8.15,7.99,8.11,8.03,0.08,0.9963,81254.77,65569.553
2019-12-04,600602.SH,8.03,8.14,7.97,8.03,8.08,-0.05,-0.6188,52009.90,41914.993
2019-12-03,600602.SH,7.92,8.10,7.87,8.08,7.88,0.20,2.5381,58209.52,46490.771
2019-12-02,600602.SH,7.91,8.01,7.85,7.88,7.97,-0.09,-1.1292,40127.22,31745.080
2019-12-20,600602.SH,8.39,8.43,8.24,8.37,8.40,-0.03,-0.3571,95244.13,79336.613
2019-12-19,600602.SH,8.40,8.48,8.32,8.40,8.41,-0.01,-0.1189,91483.98,76760.001
2019-12-18,600602.SH,8.44,8.53,8.34,8.41,8.42,-0.01,-0.1188,116722.06,98173.628
2019-12-17,600602.SH,8.35,8.47,8.31,8.42,8.30,0.12,1.4458,137504.13,115454.344
2019-12-16,600602.SH,8.05,8.35,7.99,8.30,8.05,0.25,3.1056,148648.97,121642.081
2019-12-13,600602.SH,8.05,8.08,7.93,8.05,8.05,0.00,0.0000,94883.19,76068.546
2019-12-12,600602.SH,8.04,8.06,7.89,8.05,8.04,0.01,0.1244,88665.12,70615.546
2019-12-11,600602.SH,8.20,8.20,7.99,8.04,8.19,-0.15,-1.8315,81336.39,65534.671

In [135]:
df3.sort_index(inplace=True)

In [136]:
df3

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2019-12-02,600602.SH,7.91,8.01,7.85,7.88,7.97,-0.09,-1.1292,40127.22,31745.080
2019-12-03,600602.SH,7.92,8.10,7.87,8.08,7.88,0.20,2.5381,58209.52,46490.771
2019-12-04,600602.SH,8.03,8.14,7.97,8.03,8.08,-0.05,-0.6188,52009.90,41914.993
2019-12-05,600602.SH,8.05,8.15,7.99,8.11,8.03,0.08,0.9963,81254.77,65569.553
2019-12-06,600602.SH,8.07,8.11,8.00,8.06,8.11,-0.05,-0.6165,52099.91,41926.983
2019-12-09,600602.SH,8.09,8.19,8.04,8.16,8.06,0.10,1.2407,68311.12,55465.699
2019-12-10,600602.SH,8.14,8.22,8.10,8.19,8.16,0.03,0.3676,61111.63,49869.217
2019-12-11,600602.SH,8.20,8.20,7.99,8.04,8.19,-0.15,-1.8315,81336.39,65534.671
2019-12-12,600602.SH,8.04,8.06,7.89,8.05,8.04,0.01,0.1244,88665.12,70615.546
2019-12-13,600602.SH,8.05,8.08,7.93,8.05,8.05,0.00,0.0000,94883.19,76068.546
2019-12-16,600602.SH,8.05,8.35,7.99,8.30,8.05,0.25,3.1056,148648.97,121642.081
2019-12-17,600602.SH,8.35,8.47,8.31,8.42,8.30,0.12,1.4458,137504.13,115454.344
2019-12-18,600602.SH,8.44,8.53,8.34,8.41,8.42,-0.01,-0.1188,116722.06,98173.628
2019-12-19,600602.SH,8.40,8.48,8.32,8.40,8.41,-0.01,-0.1189,91483.98,76760.001
2019-12-20,600602.SH,8.39,8.43,8.24,8.37,8.40,-0.03,-0.3571,95244.13,79336.613

In [137]:
df = pd.read_csv("/Users/yulin/workspace/extreme_quant/dataset/stock_sse/history/600000.SH.csv")

In [141]:
df.set_index("trade_date", inplace=True)

In [144]:
df.index = pd.to_datetime(df.index)

In [145]:
df.index

DatetimeIndex(['2000-01-04', '2000-01-05', '2000-01-06', '2000-01-07',
               '2000-01-10', '2000-01-11', '2000-01-12', '2000-01-13',
               '2000-01-14', '2000-01-17',
               ...
               '2022-11-29', '2022-11-30', '2022-12-01', '2022-12-02',
               '2022-12-05', '2022-12-06', '2022-12-07', '2022-12-08',
               '2022-12-09', '2022-12-12'],
              dtype='datetime64[ns]', name='trade_date', length=5442, freq=None)

In [29]:
import pandas as pd
df = pd.read_csv("/Users/yulin/workspace/extreme_quant/dataset/stock_sse/symbol.csv")
# df.reset_index(inplace=True)
# df.set_index("ts_code", inplace=True)
df.head()

,Unnamed: 0,ts_code,symbol,name,area,industry,fullname,market,exchange,curr_type,list_status,list_date,is_hs
0,0,600000.SH,600000,浦发银行,上海,银行,上海浦东发展银行股份有限公司,主板,SSE,CNY,L,19991110,H
1,1,600004.SH,600004,白云机场,广东,机场,广州白云国际机场股份有限公司,主板,SSE,CNY,L,20030428,N
2,2,600006.SH,600006,东风汽车,湖北,汽车整车,东风汽车股份有限公司,主板,SSE,CNY,L,19990727,N
3,3,600007.SH,600007,中国国贸,北京,园区开发,中国国际贸易中心股份有限公司,主板,SSE,CNY,L,19990312,H
4,4,600008.SH,600008,首创环保,北京,环境保护,北京首创生态环保集团股份有限公司,主板,SSE,CNY,L,20000427,H

In [22]:
df["600006.SH"]

KeyError: '600006.SH'

In [15]:
df = pd.read_csv("/Users/yulin/workspace/extreme_quant/600000.SH.csv")
df.head()

,trade_date,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,20000104,600000.SH,24.98,25.78,24.75,25.57,24.75,0.82,3.31,44961.0,113946.783
1,20000105,600000.SH,25.57,25.98,25.15,25.28,25.57,-0.29,-1.13,52528.0,134465.427
2,20000106,600000.SH,25.18,26.30,25.05,25.99,25.28,0.71,2.81,62297.0,160059.798
3,20000107,600000.SH,26.30,27.50,26.12,26.90,25.99,0.91,3.50,213553.0,575751.082
4,20000110,600000.SH,27.00,27.85,26.71,27.25,26.90,0.35,1.30,165397.0,450453.518

In [16]:
df.set_index('trade_date', inplace=True)

In [17]:
df.index

Int64Index([20000104, 20000105, 20000106, 20000107, 20000110, 20000111,
            20000112, 20000113, 20000114, 20000117,
            ...
            20221129, 20221130, 20221201, 20221202, 20221205, 20221206,
            20221207, 20221208, 20221209, 20221212],
           dtype='int64', name='trade_date', length=5442)

In [19]:
df.index = pd.to_datetime(df.index, format='%Y%m%d')
df.head()

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2000-01-04,600000.SH,24.98,25.78,24.75,25.57,24.75,0.82,3.31,44961.0,113946.783
2000-01-05,600000.SH,25.57,25.98,25.15,25.28,25.57,-0.29,-1.13,52528.0,134465.427
2000-01-06,600000.SH,25.18,26.30,25.05,25.99,25.28,0.71,2.81,62297.0,160059.798
2000-01-07,600000.SH,26.30,27.50,26.12,26.90,25.99,0.91,3.50,213553.0,575751.082
2000-01-10,600000.SH,27.00,27.85,26.71,27.25,26.90,0.35,1.30,165397.0,450453.518

In [20]:
df["20000101":"20000110"]

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2000-01-04,600000.SH,24.98,25.78,24.75,25.57,24.75,0.82,3.31,44961.0,113946.783
2000-01-05,600000.SH,25.57,25.98,25.15,25.28,25.57,-0.29,-1.13,52528.0,134465.427
2000-01-06,600000.SH,25.18,26.30,25.05,25.99,25.28,0.71,2.81,62297.0,160059.798
2000-01-07,600000.SH,26.30,27.50,26.12,26.90,25.99,0.91,3.50,213553.0,575751.082
2000-01-10,600000.SH,27.00,27.85,26.71,27.25,26.90,0.35,1.30,165397.0,450453.518

In [48]:
ts.set_token("b9d8623c7dbde160e75147e2b47588810dd8dc3033ec8cadc9f64f53")
PRO = ts.pro_api()
df = PRO.query("daily", ts_code="600000.SH")

In [50]:
df.set_index("trade_date", inplace=True)
df.sort_index(inplace=True)
df.head()

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
19991110,600000.SH,29.50,29.80,27.00,27.75,10.00,17.75,177.50,1740851.0,4859102.435
19991111,600000.SH,27.58,28.38,27.53,27.71,27.75,-0.04,-0.14,294035.0,821582.199
19991112,600000.SH,27.86,28.30,27.77,28.05,27.71,0.34,1.23,150080.0,421591.623
19991115,600000.SH,28.20,28.25,27.70,27.75,28.05,-0.30,-1.07,119211.0,332952.812
19991116,600000.SH,27.88,27.97,26.48,26.55,27.75,-1.20,-4.32,232231.0,628908.296

In [51]:
df.to_csv("test.csv")

In [59]:
import pandas as pd
df = pd.read_csv("/Users/yulin/workspace/extreme_quant/600000.SH.csv")

In [61]:
df2 = df.set_index("trade_date")
df2.sort_index(inplace=True)
df2.index = pd.to_datetime(df2.index, format='%Y%m%d')
df3 = df2["20000201":"20000310"]
df3.head()

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2000-02-14,600000.SH,26.00,27.48,25.50,27.20,25.04,2.16,8.63,237391.0,628039.000
2000-02-15,600000.SH,27.20,27.48,25.65,25.68,27.20,-1.52,-5.59,262677.0,693158.484
2000-02-16,600000.SH,25.50,25.55,24.91,25.20,25.68,-0.48,-1.87,190691.0,478863.316
2000-02-17,600000.SH,25.25,26.40,24.23,24.90,25.20,-0.30,-1.19,230448.0,579973.766
2000-02-18,600000.SH,24.90,25.00,24.30,24.68,24.90,-0.22,-0.88,96935.0,237689.141

In [2]:
import pandas as pd

In [77]:
f_stock = "600000.SH.csv"
df = pd.read_csv(f_stock)
df.set_index("trade_date", inplace=True)
df.index = pd.to_datetime(df.index, format='%Y%m%d')

FEATURES_HEAD = ["open", "high", "low", "close"]

df = df[FEATURES_HEAD + ["BuySellPoint_qc_0.2_sp_0.02"]] # trade_date 用于可视化

In [78]:
df.head()

             open   high    low  close  BuySellPoint_qc_0.2_sp_0.02
trade_date
2000-01-04  24.98  25.78  24.75  25.57                          0.0
2000-01-05  25.57  25.98  25.15  25.28                          0.0
2000-01-06  25.18  26.30  25.05  25.99                          0.0
2000-01-07  26.30  27.50  26.12  26.90                         -0.9
2000-01-10  27.00  27.85  26.71  27.25                         -1.0

In [92]:
import datetime
df["2012-02-05":"2012-02-12"][-16:]

            open  high   low  close  BuySellPoint_qc_0.2_sp_0.02
trade_date
2012-02-06  9.46  9.51  9.29   9.39                          0.0
2012-02-07  9.32  9.36  9.18   9.24                          0.0
2012-02-08  9.23  9.48  9.23   9.45                          0.0
2012-02-09  9.45  9.48  9.36   9.40                          0.0
2012-02-10  9.36  9.48  9.32   9.37                          0.0

In [37]:
df2 = df.reset_index()

In [40]:
df2

  trade_date   open   high    low  close  BuySellPoint_qc_0.2_sp_0.02
0 2000-01-04  24.98  25.78  24.75  25.57                          0.0
1 2000-01-05  25.57  25.98  25.15  25.28                          0.0
2 2000-01-06  25.18  26.30  25.05  25.99                          0.0
3 2000-01-07  26.30  27.50  26.12  26.90                         -0.9
4 2000-01-10  27.00  27.85  26.71  27.25                         -1.0

In [58]:
i = df2[df2.trade_date=="2001-04-14"].index
print(i)
# df2[i-2:i+1]

Int64Index([], dtype='int64')